//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personalplanung.Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenutzerKonto
    {
        public int ID_Account { get; set; }
        public string Benutzername { get; set; }
        public string Passwort { get; set; }
        public Nullable<bool> IstAdmin { get; set; }
        public Nullable<int> Angestellter { get; set; }
    
        public virtual Mitarbeiter Mitarbeiter { get; set; }
    }
}
